# Generated by Django 3.2.6 on 2021-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Branch', models.CharField(max_length=64)),
                ('Highercollagename', models.CharField(max_length=64)),
                ('Can_you_writecode', models.CharField(max_length=64)),
                ('TechinalSkills', models.CharField(max_length=64)),
                ('yourworkDomain', models.CharField(max_length=64)),
                ('yearofExp', models.IntegerField()),
            ],
        ),
    ]
